### ISSUE TITLE
Требуется пример

### ISSUE THREAD

**Issue by shab2** [fukanchik/pg0#4]
Добрый день. 
Интересная возможность в Вашем проекте.
Не могли бы Вы продемонстрировать все необходимы шаги на тестовой среде, чтобы продемострировать от git clone до запуска pg0 на бекапе?

**Comment by fukanchik** [comment]
Добрый день.
Я не уверен что утилита будет работать с современной версией pg_probackup, там были изменения в форматах файлов. На 2.5.10 точно будет работать.

Вот здесь примеры использования:
https://github.com/fukanchik/pg0/blob/main/basic.sh
https://github.com/fukanchik/pg0/blob/main/two.sh

**Comment by fukanchik** [comment]
Я добавил пример как это запустить в докере на версиях postgres 16.0 + probackup v2.5.13.
https://github.com/fukanchik/pg0?tab=readme-ov-file#запуск-примера-в-докере
